service: apigw-opa-authz
frameworkVersion: '2'
configValidationMode: warn

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  timeout: 10 
  logRetentionInDays: 1
  stage: dev
  region: ap-southeast-2

  apiGateway:
    minimumCompressionSize: 1024

  httpApi:
    cors: true
    payload: "2.0"
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizerFunc
        payloadVersion: '2.0'
        enableSimpleResponses: true

package:
  patterns:
    - '!./**'
    - ./bin/**


functions:
  authorizerFunc:
    handler: bin/authz
  service1:
    handler: bin/service1
    events:
      - httpApi:
          path: /service1/9/some
          method: get
          authorizer:
            name: customAuthorizer
  service2:
    handler: bin/service2
    events:
      - httpApi:
          path: /service2
          method: get
          authorizer:
            name: customAuthorizer